package com.company.project.model;

// Generated 2011-11-24 10:21:16 by Hibernate Tools 3.4.0.CR1


import com.company.project.common.persistence.IdEntity;
import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.*;
import java.util.Date;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name = "attachment")
@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Attachment extends IdEntity {

	private static final long serialVersionUID = -7761227854582585540L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
	private String contentType;
	private String fileName;
	private String fileUrl;
	private Integer fileSize;
	private Integer createBy;
	private Date createTime;
	private Boolean enable;

	// helper
	private byte[] bytes;
	private String dimension;
	private int width;
	private int height;

	public Attachment() {
		this.enable = true;
		this.createTime = new Date();
	}
    /**
     * @return id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

	@Column(nullable=false)
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Transient
	public String getName() {
		return StringUtils.substringBefore(fileName, ".");
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileUrl() {
		return this.fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	public Integer getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	public Integer getCreateBy() {
		return createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Boolean getEnable() {
		return this.enable;
	}

	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	@Transient
	public String getSuffix() {
		return "."+StringUtils.substringAfterLast(fileName, ".");
	}

	@Transient
	public byte[] getBytes() {
		return bytes;
	}

	public void setBytes(byte[] bytes) {
		this.bytes = bytes;
	}

	@Transient
	public String getDimension() {
		return dimension;
	}

	public void setDimension(String dimension) {
		this.dimension = dimension;
	}

	@Transient
	public int getWidth() {
		return width;
	}

	public void setWidth(int width) {
		this.width = width;
	}

	@Transient
	public int getHeight() {
		return height;
	}

	public void setHeight(int height) {
		this.height = height;
	}


}
